### ISSUE TITLE
getProject benötigt weitere Informationen

### ISSUE THREAD

**Issue by fkloepper** [Exormeter/Blockchain#2]
getProject muss zusätzlich die Informationen Laufzeit und Funding-Ziel zurückgeben

**Comment by Exormeter** [comment]
Projects haben nun ein Ziel und eine Laufzeit. Sollte Ziel in Laufzeit nicht erreicht werden, können die gezahlten Beträge über requestPayback() auf die Investorkonten zurückgezahlt werden. Request können nun erst erstellt werden, wenn das Ziel erreicht wurde
