### ISSUE TITLE
Event emitten bei Abgabe von Vote

### ISSUE THREAD

**Issue by fkloepper** [Exormeter/Blockchain#3]

**Comment by Exormeter** [comment]
Ich hab für die Vote-Funktion ein Event erstellt das die neue Anzahl an Votes enthält, kannst mal testen ob es funktioniert

**Comment by Exormeter** [comment]
Es wird im ContractHub nun ein Event emittet, wenn ein neues Projekt erfolgeich erzeugt wurde.

In den eigentlichen ContractProject gibt es nun ein Event bei Erstellung eines Requests und BackingOption erstellt. Falls du noch andere Events haben willst musst du mir schreiben
