### ISSUE TITLE
Date-Prüfung beim Anlegen eines Projekts

### ISSUE THREAD

**Issue by fkloepper** [Exormeter/Blockchain#5]
Contract nimmt lediglich einen beliebigen Int an. Muss auf zukünftigen Timestamp beschränkt sein

**Comment by Exormeter** [comment]
Wie soll es auf einen Timestamp beschränkt werden wenn ein normaler Timestamp nur ein Integer ist?

Edit: Ach so, ich habs so gelesen das es zukünftig auf Timestamps begrenzt werden soll😅

**Comment by fkloepper** [comment]
Genau, der int muss halt einfach ein valider Timestamp sein, der in der Zukunft liegt

**Comment by Exormeter** [comment]
Date werden nun in addRequest() und addProject() daraufhin geprüft, ob sie in der Vergangenheit liegen
