### ISSUE TITLE
Deadline für Votes sollte mindestens einen Tag betragen

### ISSUE THREAD

**Issue by fkloepper** [Exormeter/Blockchain#7]
Ein Projektersteller könnte die Anfragen-Voting-Dauer auf einen sehr kurzen Zeitraum setzen, wodurch er effektiv die Votes auf eine kleine (manipulierte) Gruppe beschränken könnte.

**Comment by Exormeter** [comment]
Ist nicht möglich, da die Mehrzahl der Stimmen immer von der gesamten Mehrheit ausgeht, "Nicht-Wähler" werden also auch berücksichtigt.
