### ISSUE TITLE
State zu Projekten halten

### ISSUE THREAD

**Issue by fkloepper** [Exormeter/Blockchain#9]
Über den Contract sollte per getProject() der aktuelle State eines Projekts abrufbar sein. 

0: Initialisierung (Backing-Optionen hinzufügbar)
1: Aktiv (Investoren können Backing-Optionen wählen)
2: Ziel erreicht (Funding-Ziel wurde erreicht / Investoren können noch verfügbare Backing-Optionen wählen)
3: Deadline abgeschlossen (Erfolgreich / Projekt-Leiter kann Anträge stellen)
4: Deadline abgeschlossen (Funding-Ziel nicht erreicht / Refund möglich)

**Comment by Exormeter** [comment]
States wurden erstellt

**Comment by Exormeter** [comment]
Siehe WhatsApp, Erinnerung an mich

**Comment by Exormeter** [comment]
Sollte jetzt gehen, kann die States wo Deadlines ablaufen allerdings schlecht testen, müsstest du nachher mal gucken. State 0, 1, 2 gehen aber auf jeden Fall.

**Comment by Exormeter** [comment]
Sollte gehen, keine beschwerden mehr gehört
